$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$colors = @{
  Chocolate='#56382d'; Taupe='#8c7363'; Black='#1f2020'; Olive='#6f7350'; Burgundy='#6b2133'; Plum='#4a2740'; Ivory='#ece6d8'; Camel='#b2804f'
}
$products = @(
  @{slug='oval';name='Danzla Oval';price=5900;default='Chocolate';colors=@('Chocolate','Taupe','Black','Olive','Burgundy','Plum','Ivory','Camel');desc='Компактная сумка из экозамши с выразительной овальной ручкой из натурального дерева. Архитектурный силуэт сохраняет мягкость материала, а съёмный ремень позволяет менять способ ношения.';details=@('Экозамша с мягкой фактурой','Овальная ручка из натурального дерева','Основное отделение и внутренние карманы','Съёмный плечевой ремень')},
  @{slug='rondo';name='Danzla Rondo';price=6000;default='Chocolate';colors=@('Chocolate','Taupe','Black','Olive','Burgundy');desc='Сумка из экозамши с круглой ручкой из натурального дерева. Закрывается на молнию и магнит, подходит для ношения в руке и на плече.';details=@('Экозамша и натуральное дерево','Круглая деревянная ручка','Молния и скрытый магнит','Два съёмных ремня')},
  @{slug='vela';name='Danzla Vela';price=5800;default='Chocolate';colors=@('Chocolate','Taupe','Black','Olive','Burgundy','Ivory');desc='Компактная асимметричная сумка с одним основным отделением. Пластичный корпус, короткая ручка и съёмный ремень дают три сценария ношения.';details=@('Асимметричный крой','Одно основное отделение','Застёжка-молния','Короткая ручка и съёмный ремень')},
  @{slug='duna';name='Danzla Duna';price=5200;default='Chocolate';colors=@('Chocolate','Taupe','Black','Olive','Burgundy');desc='Вместительная сумка-тоут с двумя длинными ручками. Чистая геометрия и центральный шов подчёркивают глубокую фактуру экозамши.';details=@('Мягкая фактурная экозамша','Две длинные ручки','Вместительный формат','Фирменный металлический логотип')},
  @{slug='half-moon';name='Danzla Half Moon';price=5600;default='Chocolate';colors=@('Chocolate','Taupe','Black','Olive','Burgundy','Ivory');desc='Маленькая сумка хобо с мягким силуэтом полумесяца. Плавная линия корпуса удобно ложится под руку и поддерживает как повседневные, так и вечерние образы.';details=@('Силуэт полумесяца','Одно основное отделение','Мягкая конструкция','Регулируемый плечевой ремень')},
  @{slug='triangle';name='Danzla Triangle';price=6200;default='Black';colors=@('Black','Olive','Burgundy');desc='Сумка из экозамши с цельной ручкой из натурального дерева и треугольным вырезом. Контраст мягкого корпуса и архитектурной ручки формирует узнаваемый силуэт.';details=@('Экозамша и натуральное дерево','Треугольный вырез в ручке','Мягкий объёмный корпус','Съёмный плечевой ремень')},
  @{slug='weave';name='Danzla Weave';price=5400;default='Chocolate';colors=@('Chocolate','Black','Olive','Ivory');desc='Сумка через плечо с декоративным переплетением панелей на передней части. Ручная пластика линий делает лаконичный силуэт выразительным.';details=@('Декоративное переплетение панелей','Мягкая конструкция','Плечевой ремень','Фирменный металлический логотип')}
)
function Image-List($p,$color){
  $s=$p.slug;$c=$color.ToLower();$base="../../assets-materials/products/$s"
  if($s -eq 'oval' -and $c -eq 'chocolate'){return @("$base/oval-chocolate-studio-angle.png","$base/oval-chocolate-editorial.png","$base/oval-chocolate-interior.png","$base/oval-chocolate-macro-handle.png","$base/oval-chocolate-details-grid.png","$base/oval-chocolate-material-macro.png")}
  if($s -eq 'rondo' -and $c -eq 'chocolate'){return @("$base/rondo-chocolate-studio-angle.png","$base/rondo-chocolate-editorial.png","$base/rondo-chocolate-interior.png","$base/rondo-chocolate-macro-handle.png","$base/rondo-chocolate-details-grid.png","$base/rondo-chocolate-material-macro.png")}
  if($s -eq 'vela' -and $c -eq 'chocolate'){return @("$base/vela-chocolate-studio-angle.png","$base/vela-lifestyle-architectural.png","$base/vela-chocolate-capacity.png","$base/vela-chocolate-macro-handle.png","$base/vela-chocolate-details-grid.png","$base/vela-chocolate-material-macro.png")}
  return @("$base/$s-$c-studio.png","$base/$s-$c-lifestyle.png","$base/$s-$c-capacity.png","$base/$s-$c-detail.png","$base/$s-$c-details-grid.png","$base/$s-$c-material-macro.png")
}
foreach($p in $products){
  $variantRows=@();foreach($c in $p.colors){$imgs=(Image-List $p $c)|ForEach-Object{'"'+$_+'"'};$variantRows += "    `"$c`": {images:[$($imgs -join ',')]}"}
  $swatches=@();foreach($c in $p.colors){$pressed=($c -eq $p.default).ToString().ToLower();$swatches += "<li><button class=`"swatch`" type=`"button`" style=`"--swatch:$($colors[$c])`" data-color=`"$c`" aria-label=`"Цвет $c`" aria-pressed=`"$pressed`"></button></li>"}
  $detailItems=($p.details|ForEach-Object{"<li>$_</li>"}) -join ''
  $hero=(Image-List $p $p.default)[1]
  $price='{0:N0}' -f $p.price;$price=$price.Replace([char]0xA0,' ')
  $html=@"
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="$($p.desc)"><title>$($p.name)</title><link rel="icon" href="../../img/danzla-logo.webp"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600&family=Prata&display=swap" rel="stylesheet"><link rel="stylesheet" href="../../assets/css/handbag-product.css"></head>
<body><header class="site-header"><nav><a href="../../index.html">Главная</a><a href="../../collections/handbags/index.html">Сумки</a></nav><a class="site-header__logo" href="../../index.html"><img src="../../img/danzla-logo.webp" alt="DanZla"></a><nav class="site-header__right"><a href="../../favorites/index.html">Избранное <span class="counter" data-favorites-count>0</span></a><a href="../../checkout/index.html">Корзина <span class="counter" data-cart-count>0</span></a></nav></header>
<main><section class="product"><div class="gallery" aria-label="Фотографии товара"><figure data-kind="studio"><img alt=""></figure><figure><img alt=""></figure><figure data-kind="capacity"><img alt=""></figure><figure><img alt=""></figure><figure><img alt=""></figure><figure><img alt=""></figure></div><aside class="product-info"><div class="breadcrumbs"><a href="../../collections/handbags/index.html">Сумки</a> / $($p.name)</div><p class="eyebrow">DanZla bags</p><h1>$($p.name.Replace('Danzla ',''))</h1><p class="edition" id="product-edition">Edition $($p.default)</p><p class="price">$price ₽</p><p class="description">$($p.desc)</p><div class="choice"><span>Цвет</span><span id="product-color">$($p.default)</span></div><ul class="swatches">$($swatches -join '')</ul><div class="actions"><button class="buy" type="button" data-buy>Добавить в корзину</button><button class="wishlist" type="button" data-wishlist aria-label="Добавить в избранное" aria-pressed="false">♡</button></div><p class="stock">В наличии — отправим в течение двух рабочих дней</p><div class="details"><details open><summary>Описание</summary><div class="details__body">$($p.desc)</div></details><details><summary>Материалы и детали</summary><div class="details__body"><ul>$detailItems</ul></div></details><details><summary>Доставка и возврат</summary><div class="details__body">Доставка по России. Бесплатный возврат в течение 14 дней при сохранении товарного вида.</div></details></div><p class="sku" id="product-sku"></p></aside></section><section class="story"><img src="$hero" alt="$($p.name) в образе"><div class="story__copy"><small>Designed by DanZla</small><h2>Форма, которую хочется держать в руках</h2><p>$($p.desc) Каждый ракурс галереи показывает реальный силуэт, конструкцию, вместимость и фактуру материала.</p></div></section></main>
<footer class="footer"><img class="footer__logo" src="../../img/danzla-logo.webp" alt="DanZla"><div class="footer__row"><a href="../../collections/handbags/index.html">Все сумки</a><a href="../../favorites/index.html">Избранное</a><a href="../../checkout/index.html">Оформление заказа</a><span>© 2026 DanZla</span></div></footer>
<script>window.HANDBAG_PRODUCT={slug:'$($p.slug)',name:'$($p.name)',price:$($p.price),defaultColor:'$($p.default)',labels:['студийный ракурс','в образе','вместимость','деталь конструкции','четыре детали','макро материала'],variants:{`n$($variantRows -join ",`n")`n}};</script><script src="../../assets/js/storefront.js"></script><script src="../../assets/js/handbag-product.js"></script></body></html>
"@
  $dir=Join-Path $root "products\$($p.slug)";New-Item -ItemType Directory -Force -Path $dir|Out-Null
  [IO.File]::WriteAllText((Join-Path $dir 'index.html'),$html,(New-Object Text.UTF8Encoding($false)))
}
